- hosts: frontend
  serial: 1
  become: true
  roles:
    - apt
    - docker
    - set_hostname
    - ufw
    - zerotier
    - ssh_hardening


  tags: frontend

- hosts: backend
  become: true
  roles:
    - apt
    - docker
    - set_hostname
    - ufw
    - ssh_hardening

    
  tags: backend
