- hosts: frontend
  serial: 1
  become: true
  roles:
    - common
    - set_hostname
    - nat
    - nat_firewall
  tags: frontend

- hosts: backend
  become: true
  roles:
    - apt
    - set_hostname
    - nat_firewall
  tags: backend
